name: Helm OCI Chart Release

on:
  workflow_dispatch:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.4.1
        with:
          registry: ghcr.io
          repository: dungdm93/helm
          name: spark-proxy
          tag: 1.0.0  # ${{ github.ref_name }}
          path: deploy/chart
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: true
